language: java
install: true

dist: trusty
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/gradle-5.6
    - $HOME/.gradle

before_install:
  - if [ ! -d "$HOME/gradle-5.6" ];
    then (wget -P $HOME https://services.gradle.org/distributions/gradle-5.6-bin.zip
    && unzip -d $HOME $HOME/gradle-5.6-bin.zip);
    fi
  - export GRADLE_HOME=$HOME/gradle-5.6
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script: gradle check
