language: java
install: true

dist: trusty
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/gradle-4.10.3
    - $HOME/.gradle

before_install:
  - if [ ! -d "$HOME/gradle-4.10.3" ];
    then (wget -P $HOME https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
    && unzip -d $HOME $HOME/gradle-4.10.3-bin.zip);
    fi
  - export GRADLE_HOME=$HOME/gradle-4.10.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script: gradle check
