language: java
install: true

dist: trusty
jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/gradle-5.6.4
    - $HOME/.gradle

before_install:
  - if [ ! -d "$HOME/gradle-5.6.4" ];
    then (wget -P $HOME https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
    && unzip -d $HOME $HOME/gradle-5.6.4-bin.zip);
    fi
  - export GRADLE_HOME=$HOME/gradle-5.6.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script: gradle check
